name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install lua5.2
      run: sudo apt-get install lua5.2

    - name: lint
      uses: mrcjkb/lua-typecheck-action@v1.0.0
      with:
        checkLevel: Error
        configPath: ".luarc.json"
    
    - name: unit test
      run: lua test-suite.lua -v
      working-directory: tests
